### ISSUE TITLE
Requirement parser does not support arbitrary equality in legacy parentheses format

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging#336] opened 2020-10-08 16:29 UTC
These all work as expected:

```pycon
>>> Requirement('foo==1.0')
<Requirement('foo==1.0')>
>>> Requirement('foo===1.0')
<Requirement('foo===1.0')>
>>> Requirement('foo (==1.0)')
<Requirement('foo==1.0')>
```

But not this:

```pycon
>>> Requirement('foo (===1.0)')
Traceback (most recent call last):
  File "packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "pyparsing.py", line 1955, in parseString
    raise exc
  File "pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found '('  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'(===1.0)'": Expected stringEnd
```

**Comment by di** [comment] 2020-10-08 17:18
The issue is that this operator matches everything after it that is not whitespace as the version:

```
>>> Requirement('foo===1.0)').specifier
<SpecifierSet('===1.0)')>
```

You'd need to do this instead::

```
>>> Requirement('foo (===1.0 )').specifier
===1.0
<SpecifierSet('===1.0')>
```

See here: https://github.com/pypa/packaging/blob/59e14881910bf836c43b7d319ea08ab321ccfb39/packaging/specifiers.py#L328-L338

I'm not sure this is a bug.

**Comment by uranusjr** [comment] 2020-10-08 17:56
I’d say it is. `foo (===1.0` is not a valid requirement, so The requirement parser should not pass in the closing one to the specifier parser if there’s an opening one. IOW `Requirement('foo (===1.0)')`, `Specifier` should get `===1.0` instead of `===1.0)`.

The rules in `requirements.py` are defined as

```python
```

**Comment by pradyunsg** [comment] 2020-10-11 12:40
The behavior @uranusjr's suggesting makes sense to me and IMO if the standards say otherwise, we should update them.

**Comment by gmmephisto** [comment] 2020-11-20 17:24
I'm facing this issue while installing the wheel that built with arbitrary equal for dependency in `requirements.txt`. There is a traceback on `pip install`:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 437, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2978, in extras
    return [dep for dep in self._dep_map if dep]
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3033, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Parse error at "'(===1.1.'": Expected stringEnd
```

As I understand pep440 correctly, arbitrary equality is using not only for "escape hatch", but also for comparing versions without taking into account local versions (https://www.python.org/dev/peps/pep-0440/#arbitrary-equality) which may be useful and should not break `pip install`.

**Comment by uranusjr** [comment] 2021-02-24 08:50
Gental ping since this is surfaced in pip again recently. #353 is a reasonable fix to this IMO.

**Comment by IceTDrinker** [comment] 2021-04-07 12:38
Hello, any news on this ?

**Comment by uranusjr** [comment] 2021-04-07 12:54
I don’t think anyone is actively working on this. Feel free to dive into the parser code.

**Comment by IceTDrinker** [comment] 2021-04-07 13:09
Well the question is related to the fact you indicate #353 is a reasonable fix for this so I was wondering if there were plans to merge it ?

**Comment by uranusjr** [comment] 2021-04-07 13:17
> I was wondering if there were plans to merge it?

Probably not, I guess? I don’t have permissions to merge PRs here and can’t definitely answer this.

The change is reasonable, but far from perfect. The correct logic should only detect the opening parenthesis after the package identifier, and remove the closing one only if there is an opening parenthesis at the correct location. This is likely doable with some parser logic changes, but I have not looked into actually trying it myself. This is very low priority, to be honest.

**Comment by IceTDrinker** [comment] 2021-04-07 13:19
Ok, I might take a look at the open PR and try to iron it out

Cheers

**Comment by brettcannon** [comment] 2022-08-14 23:22
https://github.com/pypa/packaging/pull/353/ is a PR to fix this. Does the approach seem reasonable to people?

**Comment by uranusjr** [comment] 2022-08-15 05:00
Now that we have a hand-crafted parser, I’d actually expect it be able to handle parenthesis-matching directly.

**Comment by pradyunsg** [comment] 2022-12-07 01:03
#624 does that updating, and makes it possible to use this format.

```
❯ echo 'name(===arbitrarystring)' | python -c "from packaging.requirements import Requirement; print(vars(Requirement(input())))"
{'name': 'name', 'url': None, 'extras': set(), 'specifier': <SpecifierSet('===arbitrarystring')>, 'marker': None}
```

**Closed** 2022-12-07 21:50 UTC
Labels: bug, packaging.requirements
