### ISSUE TITLE
packaging complains about invalid cpython version, ending with a +

### ISSUE THREAD

**Issue by doko42** [pypa/packaging#748] opened 2023-11-23 08:35 UTC
when building cpython from the trunk, or one of the branches, the version is set to 3.12.0+, leading to errors (here in sunpy) like these:

sunpy/tests/helpers.py:49: in <module>
    if Version(python_version()) >= Version("3.10.0"):
/usr/lib/python3/dist-packages/packaging/version.py:200: in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
E   packaging.version.InvalidVersion: Invalid version: '3.12.0+'
_ ERROR collecting .pybuild/cpython3_3.12_sunpy/build/sunpy/io/special/asdf/tests/test_coordinate_frames.py

These are just temporary issues, however it makes it a bit inconvenient to use a non-release build. Possible solutions:

- Patch out the "+" from the branch build, such that it still identifies as 3.12.0. However then nothing (except for a ChangeLog) can be seen to differentiate a release build from a branch build.
- Let packaging recognize the "+" at the end as a valid version string
- Let cpython use a version which packaging understands (e.g. 3.12.0.1)

**Comment by pradyunsg** [comment] 2023-11-23 09:02
Duplicate of #678

**Closed by pradyunsg** 2023-11-23 09:02 UTC
