### ISSUE TITLE
tags.cpython_tags returns an incorrect value when run from a 32-bit VS developer prompt on a 64-bit Windows

### ISSUE THREAD

**Issue by pfmoore** [pypa/packaging#327] opened 2020-07-31 14:27 UTC
See https://github.com/pypa/pip/issues/8649.

Basically, `cpython_tags` is using `distutils.get_platform` [here](https://github.com/pypa/packaging/blob/master/packaging/tags.py#L753). It should probably be using `get_host_platform` - as far as I can tell the only difference is for cross-compilation, and (even if we accept that distutils supports cross-compilation, which I'm not sure it does) when installing wheels, we want to use the *host* platform, not the *target* platform (as we're not even building, so "target" makes no sense).

**Comment by altendky** [comment] 2020-09-24 03:53
Just hit this on GitHub Actions where my 32-bit build for pyqt5-tools was getting 64-bit `psutil` wheels etc.  Would a useful patch be roughly a copy of `get_host_platform()` minus the cross-build awareness?

**Comment by brettcannon** [comment] 2020-09-24 17:29
@altendky without looking at the code, I simply don't know.

**Comment by zooba** [comment] 2020-11-07 00:01
> So it may be better for packaging.tags to maintain its own platform tag implementation instead of depending on distutils internals.

Yes, this.

**Comment by uranusjr** [comment] 2021-04-24 05:53
I think #396 fixed this.

**Comment by puetzk** [comment] 2021-04-26 15:57
Confirmed, it now works for me, using python-3.9.4-amd64.exe via a shell launched with `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86 -host_arch=amd64"` (so `VSCMD_ARG_TGT_ARCH=x86`)

```py
from packaging import tags
[str(x) for x in tags.cpython_tags()]
```

```diff
--- pip install packaging==20.9
+++ pip install git+https://github.com/pypa/packaging@c8008265eac83ebf2c3b3c314a682abd4c101de2
-['cp39-cp39-win32', 'cp39-abi3-win32', 'cp39-none-win32', 'cp38-abi3-win32', 'cp37-abi3-win32', 'cp36-abi3-win32', 'cp35-abi3-win32', 'cp34-abi3-win32', 'cp33-abi3-win32', 'cp32-abi3-win32']
+['cp39-cp39-win_amd64', 'cp39-abi3-win_amd64', 'cp39-none-win_amd64', 'cp38-abi3-win_amd64', 'cp37-abi3-win_amd64', 'cp36-abi3-win_amd64', 'cp35-abi3-win_amd64', 'cp34-abi3-win_amd64', 'cp33-abi3-win_amd64', 'cp32-abi3-win_amd64']
```

**Comment by brettcannon** [comment] 2021-04-26 23:03
Thanks for the confirmations! Closing as fixed.

**Closed by brettcannon** 2021-04-26 23:03 UTC
Labels: bug, packaging.tags
