### ISSUE TITLE
problem pip install google.colab 

### ISSUE THREAD

**Issue by SouhaibUniv** [pypa/packaging#692] opened 2023-05-02 10:57 UTC
C:\Windows\system32>pip install google.colab

Collecting google.colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Preparing metadata (setup.py) ... done
Collecting google-auth~=1.4.0 (from google.colab)
  Using cached google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
Collecting ipykernel~=4.6.0 (from google.colab)
  Using cached ipykernel-4.6.1-py3-none-any.whl (104 kB)
Collecting ipython~=5.5.0 (from google.colab)
  Using cached ipython-5.5.0-py3-none-any.whl (758 kB)
Collecting notebook~=5.2.0 (from google.colab)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
Collecting six~=1.12.0 (from google.colab)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0 (from google.colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by brettcannon** [comment] 2023-05-02 23:49
Duplicate of https://github.com/pypa/packaging/issues/681 .

**Closed by brettcannon** 2023-05-02 23:49 UTC
