### ISSUE TITLE
support Apple's macOS 13

### ISSUE THREAD

**Issue by dimpase** [pypa/packaging#604] opened 2022-11-01 09:53 UTC
It appears that `*macosx_13_arm64.whl` wheels are not allowed, due to packaging not knowing anything about macOS 13, which
was released about a week ago.
As reported here: https://github.com/mesonbuild/meson-python/issues/160#issuecomment-1297972659
```
ERROR: scipy-1.9.3-cp310-cp310-macosx_13_arm64.whl is not a supported wheel on this platform.
```
(scipy uses meson build, which in turn uses packaging)

**Comment by brettcannon** [comment] 2022-11-01 22:45
This is actually a duplicate of #578. macOS 13 is supported, but `macosx_13` is not a wheel tag that `packaging` produces or expects (that would be `macosx_13_0`).

**Closed by brettcannon** 2022-11-01 22:45 UTC
