### ISSUE TITLE
Requiring ~=1.0.0rc2 does not permit 1.0.1

### ISSUE THREAD

**Issue by pop** [pypa/packaging#365] opened 2020-12-01 22:25 UTC
I was told to make an issue here based on https://github.com/pypa/pip/issues/9197#issuecomment-736783006

When installing two packages, `foo` which requires `bar ~= 1.0.0rc2`, and `bar == 1.0.1`, we get a failure:

```
pip install azure-mgmt-media==1.0.1 azure-mgmt==4.0.0

[... a bunch of successful installations ...]
ERROR: Cannot install azure-mgmt-media==1.0.1 and azure-mgmt==4.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested azure-mgmt-media==1.0.1
    azure-mgmt 4.0.0 depends on azure-mgmt-media~=1.0.0rc2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Based on the docs I would expect `1.0.1` to be an OK package given the dependency is on `1.0.0rc2`.

Source: https://www.python.org/dev/peps/pep-0440/#compatible-release

If this does not contradict the documentation, I would request an update to the docs to make that more obvious.

**Comment by pradyunsg** [comment] 2020-12-01 23:17
Thanks for filing this issue, and taking the time to link to the relevant section in PEP 440.

> If a pre-release, post-release or developmental release is named in a compatible release clause as V.N.suffix, then the suffix is ignored when determining the required prefix match:

> ```
> ~= 2.2.post3
> >= 2.2.post3, == 2.*
> ```

Looks like a bug we have to fix!

**Comment by di** [comment] 2020-12-02 00:36
Duplicate of #100.

**Closed by di** 2020-12-02 00:36 UTC
