### ISSUE TITLE
docs and lint command for nox are not working

### ISSUE THREAD

**Issue by deveshks** [pypa/packaging#286] opened 2020-03-29 05:55 UTC
The nox commands listed at https://packaging.pypa.io/en/latest/development/getting-started/ for `Running tests` and `Running linters`are not working and failing with `Session lint skipped: Python interpreter 3.8 not found.`

**System Information:**

OS: Mac OSX 10.15.4
Python versions installed (via pyenv)

```
$ pyenv versions
  system
  3.4.9
* 3.7.7 (set by ~/.pyenv/version)
```

**Steps to reproduce:**

1. Git clone packaging repo
2. Create a virtualenv 

```
$ cd packaging/
$ python --version
Python 3.7.7
$ python -m venv env
$ source env/bin/activate
```

3. Install nox in that virtualenv
4. Both `nox lint` and `nox docs` command fail as follows

```
(env) $ nox -s lint
nox > Running session lint
nox > Session lint skipped: Python interpreter 3.8 not found.
(env) $ nox -s docs
nox > Running session docs
nox > Session docs skipped: Python interpreter 3.8 not found.
```

I do see that in the Getting started page, it is noted that `You may not have all the required Python versions installed, in which case you will see one or more InterpreterNotFound errors.`, which I am seeing, but that shouldn't stop me from running `lint` or `docs`.

I also glanced through the source code and found that both 

https://github.com/pypa/packaging/blob/ed0a58f0dacf08c871ce7b687558d3891de75ca9/noxfile.py#L40

and

https://github.com/pypa/packaging/blob/ed0a58f0dacf08c871ce7b687558d3891de75ca9/noxfile.py#L52

are only specifying `3.8` as session, unlike tests which include other python versions too. Maybe that's where the problem lies?

**Comment by brettcannon** [comment] 2020-03-30 20:02
Yes, the lint and doc sessions require Python 3.8 to be installed. I believe without this nox will use whatever version it was installed with which could be a version of Python that we don't support. So I wouldn't classify this as a problem but a decision with consequences. 😄 

If you have anything to add @pradyunsg please do so, but otherwise I'm closing this as working as intended.

**Closed by brettcannon** 2020-03-30 20:02 UTC
