### ISSUE TITLE
Unreasonable comparisons

### ISSUE THREAD

**Issue by torsava** [pypa/packaging#320] opened 2020-07-10 16:32 UTC
Hi,
we have found that `packaging` evaluates some comparisons unreasonably / illogically.

I'll use this format:

    (version, operator, version, comparison_evaluation),

For these comparisons, `packaging` ignores equality and evaluates as if the operator was simply `<`:

    ('2.4.8', '<=', '2.4.8.*', False),
    ('2.4.8.0', '<=', '2.4.8.*', False),
    ('2.4.8.1', '<=', '2.4.8.*', False),
    ('2.4.8.post1', '<=', '2.4.8.*', False),

And in this set, also the `>` operator is evaluated wrong:

    ('2.4.8', '>', '2.4.8.*', True),
    ('2.4.8.0', '>', '2.4.8.*', True),
    ('2.4.8.1', '>', '2.4.8.*', True),
    ('2.4.8b5', '>', '2.4.8.*', True),
    ('2.4.8.post1', '>', '2.4.8.*', True),

Both these comparisons are undefined according to [PEP 440](https://www.python.org/dev/peps/pep-0440/). However, as someone will surely be using them, tests have been added for them in the Python-to-RPM-version project `pyreq2rpm`, see PR https://github.com/gordonmessmer/pyreq2rpm/pull/7.

The tests currently verify that the comparisons are consistent with this illlogical upstream behaviour. But of course, an even better solution would be to fix the behaviour.

**Comment by hroncok** [comment] 2020-07-10 17:15
A practical example:

```
$ pip install -U 'pip<=20.1.*'
...
Successfully installed pip-20.0.2
```

As much as I wrap head my around this, i would expect both 20.1.1 and 20.1 to satisfy the requirement.

**Comment by di** [comment] 2020-07-10 18:31
It's not very clear from the PEP, but prefix matching (using `.*`) is only supported for strict equality operators (`==` and `!=`). This is why prefix matching is only mentioned in the ["Version matching"](https://www.python.org/dev/peps/pep-0440/#version-matching) and ["Version exclusion"](https://www.python.org/dev/peps/pep-0440/#version-exclusion) sections.

See also these portions of the source:
https://github.com/pypa/packaging/blob/59e14881910bf836c43b7d319ea08ab321ccfb39/packaging/specifiers.py#L392-L395

https://github.com/pypa/packaging/blob/db291c7bdac5c6684b6256562903b361baf518fa/tests/test_specifiers.py#L65-L70

**Comment by gordonmessmer** [comment] 2020-07-10 19:27
I think the problem is that prefix matching on ordered comparisons aren't _defined_, but they are supported as best I can tell.  Miro posted an example of their use, above.

If I create a mostly-empty module whose setup.py includes this line:

    requirements = ["pip>=20,<=20.1.*"]

then:

```
$ python3 -m venv utest_env
$ . utest_env/bin/activate
$ pip3 install ./utest
Processing ./utest
Collecting pip<=20.1.*,>=20
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip, utest
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
    Running setup.py install for utest ... done
Successfully installed pip-20.0.2 utest-0.1.0
```

**Comment by di** [comment] 2020-07-10 20:17
It's "supported" but only by parsing it as a [`LegacySpecifier`](https://github.com/pypa/packaging/blob/59e14881910bf836c43b7d319ea08ab321ccfb39/packaging/specifiers.py#L253-L306), which is probably not what you're expecting:

```
>>> from packaging.specifiers import SpecifierSet
>>> SpecifierSet('>=20')._specs
frozenset({<Specifier('>=20')>})
>>> SpecifierSet('<=20.1.*')._specs
frozenset({<LegacySpecifier('<=20.1.*')>})
```

**Comment by di** [comment] 2020-10-20 22:45
Closing this. Legacy specifiers will be deprecated in the next release and this will emit a warning.

**Closed by di** 2020-10-20 22:45 UTC
