### ISSUE TITLE
Generic ABI wrong

### ISSUE THREAD

**Issue by henryiii** [pypa/packaging#605] opened 2022-11-01 22:26 UTC
Currently, CPython returns this: `'cpython-311-darwin'`.

And PyPy returns this: `'pypy37-pp73'`. This breaks CMake's FindPython, for example, as it assumes this is a valid SOABI tag, and it's not, it's missing the platform.

PyPy tried to fix the return value to match CPython (to `'pypy37-pp73-darwarn'` etc., in https://foss.heptapod.net/pypy/pypy/-/issues/3816), but `packaging` has this:

https://github.com/pypa/packaging/blob/0031046f7fad649580bc3127d1cef9157da0dd79/packaging/tags.py#L228-L231

This assumes the `SOABI` to have the PyPy form, which is not how CPython has it. This is only correct for CPython because this never triggers for CPython, there is a custom implementation at https://github.com/pypa/packaging/blob/0031046f7fad649580bc3127d1cef9157da0dd79/packaging/tags.py#L162-L168.

Either the logic should be corrected, or there should be a custom implementation for PyPy (safer in the short term while this is fixed, I think).

**Comment by henryiii** [comment] 2022-11-01 22:45
Oops, we needed a mutex, also see #606...

**Comment by brettcannon** [comment] 2022-11-01 22:48
Closing as a dupe of https://github.com/pypa/packaging/issues/606 just because I saw the other one first. 😅

**Closed by brettcannon** 2022-11-01 22:48 UTC
