### ISSUE TITLE
expose an API to differentiate between dev/rc releases

### ISSUE THREAD

**Issue by digwanderlust** [pypa/packaging#84] opened 2016-09-01 17:17 UTC
Currently is_prerelease allows you to differentiate between a final release and pre_release.  However if your project uses both dev and rc releases there is no way using packaging to differentiate. 

We need to resort to something similar to:

```
suffix = version.public[len(version.base_version):]
components = version.base_version.split('.') + [suffix]
if suffix == '' or suffix.startswith('rc'):
```

A new attribute that allows access to the release suffix would be helpful since this is already being parsed by packaging.  Also making the components available would be useful for example:

'1.2.3rc9' - > ['1', '2', '3', 'rc9']
'1.2.3-rc9' -> ['1', '2', '3', 'rc9']
'1.2.3' -> ['1', '2', '3']

**Comment by jsirois** [comment] 2016-09-01 17:25
Even better, it would be nice to expose all 5 parsed components of a public version at the least in the `Version` object since it reflects the set-in-stone public API defined by PEP-440 (ie: there is ~no risk to exposing these 5 components via properties since their existence and semantic can't change).

**Comment by jsirois** [comment] 2016-09-01 17:27
If a maintainer agrees to all or part of the above, I'd be happy to add tests, implement and send a PR.

**Comment by vphilippon** [comment] 2016-10-20 21:15
@jsirois Have you started anything on this? I might actually have some time to spare on this myself.
@dstufft Is this something that seems reasonable and likely to be accepted?

**Comment by jsirois** [comment] 2016-10-20 23:50
@vphilippon I have not started any work on this.

**Comment by dstufft** [comment] 2016-12-01 15:42
This is kind of a duplicate of #34. I don't have any conceptual argument against this idea, devil is always in the details of course.

**Closed** 2018-02-28 04:42 UTC
