### ISSUE TITLE
[Regression]: InvalidVersion since 22.0

### ISSUE THREAD

**Issue by mexicarne** [pypa/packaging#749] opened 2023-12-03 23:39 UTC
Something about version parse was broken in 22.0. Here is the code for reproducing the issue:
```python
from packaging.version import parse
print(parse("6.7.8.9-10.el7"))
```
packaging 21.3 prints:
```python
6.7.8.9-10.el7
```

while packaging starting with 22.0 raises an exception:
```python
Traceback (most recent call last):
  File "/tmp/pp/test.py", line 5, in <module>
    print(parse("6.7.8.9-10.el7"))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pp/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/tmp/pp/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '6.7.8.9-10.el7'
```

**Comment by mexicarne** [comment] 2023-12-03 23:51
Ok, I compared the changes and it looks like it's not a regression, but instead planned removal of the LegacyVersional. Is there different way to handle the issue except the sticking to 21.3 in my project?

**Comment by pradyunsg** [comment] 2023-12-04 03:53
Duplicate of https://github.com/pypa/packaging/issues/530

Please see the discussion on that issue - it mentions packvers (GitHub seemingly hides it since there's so many back references).

**Closed by pradyunsg** 2023-12-04 03:53 UTC
