### ISSUE TITLE
How do I evaluate markers in an environment with multiple extras?

### ISSUE THREAD

**Issue by konstin** [pypa/packaging#639] opened 2022-12-10 14:04 UTC
If i have e.g. a user requesting `flask[async,dotenv]==2.2.2`, how can i check whether flask's requires_dist `asgiref (>=3.2) ; extra == 'async'` matches the current environment? I'd have imagined something like the following:

```python
from packaging.requirements import Requirement

Requirement("asgiref (>=3.2) ; extra == 'async'").marker.evaluate({"extra": ["async", "dotenv"]})
Requirement("asgiref (>=3.2) ; extra == 'async'").marker.evaluate({"extra": "async,dotenv"})
```

Neither of the above two works (packaging 22.0), and [markers.py](https://github.com/pypa/packaging/blob/c20074d749a8aff6454e2d644ecce5017d73a66b/src/packaging/markers.py) doesn't seem to have any way to handle multiple marker values.

**Comment by pradyunsg** [comment] 2022-12-10 16:55
You do it multiple times.

```
Requirement("asgiref (>=3.2) ; extra == 'async'").marker.evaluate({"extra": "async"})
Requirement("asgiref (>=3.2) ; extra == 'async'").marker.evaluate({"extra": "dotenv"})
```

**Comment by pradyunsg** [comment] 2022-12-10 17:02
Closing as a duplicate of https://github.com/pypa/packaging/issues/452

**Closed by pradyunsg** 2022-12-10 17:02 UTC
Labels: question, packaging.markers
