### ISSUE TITLE
Some pre-release spellings cannot be used in requirements

### ISSUE THREAD

**Issue by di** [pypa/packaging#653] opened 2023-01-05 16:46 UTC
The following are valid versions:
```python
>>> packaging.version.Version('1.0.0b1')
<Version('1.0.0b1')>
>>> packaging.version.Version('1.0.0-b1')
<Version('1.0.0b1')>
>>> packaging.version.Version('1.0.0-beta1')
<Version('1.0.0b1')>
>>> packaging.version.Version('1.0.0-beta.1')
<Version('1.0.0b1')>
```

The following are valid specifiers:
```python
>>> packaging.specifiers.Specifier('>=1.0.0b1')
<Specifier('>=1.0.0b1')>
>>> packaging.specifiers.Specifier('>=1.0.0-b1')
<Specifier('>=1.0.0-b1')>
>>> packaging.specifiers.Specifier('>=1.0.0-beta1')
<Specifier('>=1.0.0-beta1')>
>>> packaging.specifiers.Specifier('>=1.0.0-beta.1')
<Specifier('>=1.0.0-beta.1')>
```

The following requirements work:

```python
>>> packaging.requirements.Requirement("eth-utils<2.0.0,>=1.0.0b1")
<Requirement('eth-utils<2.0.0,>=1.0.0b1')>
>>> packaging.requirements.Requirement("eth-utils<2.0.0,>=1.0.0-b1")
<Requirement('eth-utils<2.0.0,>=1.0.0-b1')>
```

The following do not:

```python
>>> packaging.requirements.Requirement("eth-utils<2.0.0,>=1.0.0-beta1")
Traceback (most recent call last):
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 122, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 143, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_tokenizer.py", line 161, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
    eth-utils<2.0.0,>=1.0.0-beta1
             ~~~~~~~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    eth-utils<2.0.0,>=1.0.0-beta1
             ~~~~~~~~~~~~~~~~^
```

```python
>>> packaging.requirements.Requirement("eth-utils<2.0.0,>=1.0.0-beta.1")
Traceback (most recent call last):
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 122, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_parser.py", line 143, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/_tokenizer.py", line 161, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
    eth-utils<2.0.0,>=1.0.0-beta.1
             ~~~~~~~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/di/.pyenv/versions/3.11.1/lib/python3.11/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    eth-utils<2.0.0,>=1.0.0-beta.1
             ~~~~~~~~~~~~~~~~^
```

This is true for `alpha`, `beta`, and `preview` but not other pre-release spellings specified in [PEP 440](https://peps.python.org/pep-0440/#pre-release-spelling).

**Comment by pradyunsg** [comment] 2023-01-05 17:07
Duplicate of #629

**Closed by pradyunsg** 2023-01-05 17:07 UTC

**Comment by di** [comment] 2023-01-05 17:34
Ah, thanks. I saw that had been merged but missed that it hadn't been released and hadn't looked closely enough.
