### ISSUE TITLE
Missing package raising TypeError and not ImportError not getting caught and displaying unreadable errors

### ISSUE THREAD

**Issue by GoatSara** [pypa/packaging#434] opened 2021-06-08 02:14 UTC
In certain cases when packages are missing the re.Pattern will be called with a None which gives
`TypeError: expected string or bytes-like object`
instead of a readable error like
`ImportError: The _imagingft C module is not installed`

**Comment by uranusjr** [comment] 2021-06-08 18:45
Could you explain where and how you are getting this? Some examples to reproduce this message locally would be awesome.

**Comment by brettcannon** [comment] 2021-06-08 22:06
I would argue the error is correct and it's up to Pillow to potentially provide a better error message.

**Comment by GoatSara** [comment] 2021-06-08 23:42
Yeah after what I looked it seems it falls a bit more under the responsibility of Pillow but there might still be some usage for a clearer error for unparseable versions

**Comment by uranusjr** [comment] 2021-06-09 05:09
The error message could be improved for unparsable version strings, but if the caller passes in `None` (as is this case) this is probably the best `packaging` can do. So IMO this particular issue should be wontfix.

**Comment by brettcannon** [comment] 2021-06-09 19:12
Since we seem to be in general agreement for this specific situation, I'm closing this issue. Thanks all!

**Closed by brettcannon** 2021-06-09 19:12 UTC
Labels: bug, packaging.version, wontfix
