### ISSUE TITLE
Compatible release (~=) doesn't handle pre-releases correctly

### ISSUE THREAD

**Issue by calebzulawski** [pypa/packaging#427] opened 2021-05-03 03:23 UTC
From PEP 440:

> If a pre-release, post-release or developmental release is named in a compatible release clause as V.N.suffix, then the suffix is ignored when determining the required prefix match:
```
~= 2.2.post3
>= 2.2.post3, == 2.*

~= 1.4.5a4
>= 1.4.5a4, == 1.4.*
```

This rule doesn't seem to be followed:
```
>>> list(packaging.specifiers.Specifier('~=1.4.5a4').filter(['1.4.5a5', '1.4.6']))
['1.4.5a5']
```
What it should be equivalent to:
```
>>> list(packaging.specifiers.SpecifierSet('>=1.4.5a4,==1.4.*').filter(['1.4.5a5', '1.4.6']))
['1.4.5a5', '1.4.6']
```

**Comment by JevexEndo** [comment] 2022-03-03 17:55
My team just ran into this issue yesterday when our build system kept failing for some inexplicable reason. I was just wondering what it would take to resolve this issue since I noticed it's been open for around 10 months.

**Comment by brettcannon** [comment] 2022-03-03 19:57
I can't reproduce with the latest release of `packaging`:
```Python
list(packaging.specifiers.Specifier('~=1.4.5a4').filter(['1.4.5a5', '1.4.6']))
['1.4.5a5', '1.4.6']
```

I'm pre-emptively closing this as fixed.

@JevexEndo what version of `packaging` are you using? Do you have a code snippet to show how it isn't working?

**Closed by brettcannon** 2022-03-03 19:57 UTC
Labels: bug, packaging.specifiers

**Comment by JevexEndo** [comment] 2022-03-04 00:27
Ah, you're correct, the problem was the result of using pip 21.1.3 to install our requirements:
```
Collecting amulet-core~=1.6.0a0
  Downloading amulet_core-1.6.0-py3-none-any.whl (1.0 MB)
```
```
Collecting amulet-core==1.6.*,>=1.6.0a0
  Downloading amulet_core-1.6.2-py3-none-any.whl (1.0 MB)
```
As soon as I updated pip to 22.0.3, the issue went away:
```
Collecting amulet-core~=1.6.0a0
  Downloading amulet_core-1.6.2-py3-none-any.whl (1.0 MB)
```
