### ISSUE TITLE
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_3_x86_64')

### ISSUE THREAD

**Issue by dbl001** [pypa/packaging#450] opened 2021-08-03 16:31 UTC
I am trying to build tensorflow 2.5 on OS X 11.5 (Big Sur).

I am getting this error building the wheel:
```
 ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
...
traceback (most recent call last):
  File "setup.py", line 307, in <module>
    setup(
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_3_x86_64')
```
When I checked the supported tags there's 
```
% ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.


In [6]: import packaging.tags

In [13]: supported_tags = [(t)
    ...:                               for t in packaging.tags.mac_platforms()]
    ...: 
    ...: 

In [14]: print(supported_tags)
['macosx_10_16_x86_64', 'macosx_10_16_intel', 'macosx_10_16_fat64', 'macosx_10_16_fat32', 'macosx_10_16_universal', 'macosx_10_15_x86_64', 'macosx_10_15_intel', 'macosx_10_15_fat64', 'macosx_10_15_fat32', 'macosx_10_15_universal', 'macosx_10_14_x86_64', 'macosx_10_14_intel', 'macosx_10_14_fat64', 'macosx_10_14_fat32', 'macosx_10_14_universal', 'macosx_10_13_x86_64', 'macosx_10_13_intel', 'macosx_10_13_fat64', 'macosx_10_13_fat32', 'macosx_10_13_universal', 'macosx_10_12_x86_64', 'macosx_10_12_intel', 'macosx_10_12_fat64', 'macosx_10_12_fat32', 'macosx_10_12_universal', 'macosx_10_11_x86_64', 'macosx_10_11_intel', 'macosx_10_11_fat64', 'macosx_10_11_fat32', 'macosx_10_11_universal', 'macosx_10_10_x86_64', 'macosx_10_10_intel', 'macosx_10_10_fat64', 'macosx_10_10_fat32', 'macosx_10_10_universal', 'macosx_10_9_x86_64', 'macosx_10_9_intel', 'macosx_10_9_fat64', 'macosx_10_9_fat32', 'macosx_10_9_universal', 'macosx_10_8_x86_64', 'macosx_10_8_intel', 'macosx_10_8_fat64', 'macosx_10_8_fat32', 'macosx_10_8_universal', 'macosx_10_7_x86_64', 'macosx_10_7_intel', 'macosx_10_7_fat64', 'macosx_10_7_fat32', 'macosx_10_7_universal', 'macosx_10_6_x86_64', 'macosx_10_6_intel', 'macosx_10_6_fat64', 'macosx_10_6_fat32', 'macosx_10_6_universal', 'macosx_10_5_x86_64', 'macosx_10_5_intel', 'macosx_10_5_fat64', 'macosx_10_5_fat32', 'macosx_10_5_universal', 'macosx_10_4_x86_64', 'macosx_10_4_intel', 'macosx_10_4_fat64', 'macosx_10_4_fat32', 'macosx_10_4_universal']
```
What's the issue with macosx 11?

**Comment by uranusjr** [comment] 2021-08-03 17:22
See #435.

**Comment by brettcannon** [comment] 2021-08-04 00:22
Closing as a dupe of #435

**Closed by brettcannon** 2021-08-04 00:22 UTC
