### ISSUE TITLE
UnicodeEncodeError constructing a Version instance with unicode characters

### ISSUE THREAD

**Issue by PeterJCLaw** [pypa/packaging#90] opened 2016-12-18 22:45 UTC
I'm not sure what the expected support for unicode in version strings is, though at the moment the result is an unexpected error.
I found this while looking at https://github.com/rtfd/readthedocs.org/issues/2506:
``` python
In [32]: Version(u'1.2.3+941_Добавить_на_ф')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-32-febb99ecd5ec> in <module>()
----> 1 Version(u'1.2.3+941_Добавить_на_ф')

/tmp/venv/lib/python2.7/site-packages/packaging/version.pyc in __init__(self, version)
    200         match = self._regex.search(version)
    201         if not match:
--> 202             raise InvalidVersion("Invalid version: '{0}'".format(version))
    203 
    204         # Store the parsed out pieces of the version

UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-17: ordinal not in range(128)
```

Even if unicode characters in versions aren't expected to be supported, it would be great to error about that directly, rather than emitting a `UnicodeEncodeError`.

Version info:
- Python 2.7.12 (on Ubuntu 16.04)
- packaging 16.8

**Comment by ericholscher** [comment] 2017-03-28 00:36
I'm also having this issue, any other guidance?

**Comment by vphilippon** [comment] 2017-03-28 04:26
It seems non-ASCII characters are not supported in PEP 440 versions:
(From https://www.python.org/dev/peps/pep-0440/)

> To ensure local version identifiers can be readily incorporated as part of filenames and URLs, and to avoid formatting inconsistencies in hexadecimal hash representations, local version labels MUST be limited to the following set of permitted characters:
> 
> ASCII letters ( [a-zA-Z] )
> ASCII digits ( [0-9] )
> periods ( . )
> Local version labels MUST start and end with an ASCII letter or digit.

So an `UnicodeEncodeError` seems appropriate, but it could be nice to try to handle the unicode characters to raise an `InvalidVersion` instead. Although, this might mask the root cause, I'm not sure which one is best in that case.

**Comment by PeterJCLaw** [comment] 2017-03-28 08:13
I would be in favour of ensuring that consistent errors were produced; for example the ASCII character `&` does not appear to be allowed, but would yield an `InvalidVersion` error.

With regards to helping the user better understand the cause of the error, I'd suggest changing the exception text to be more specific, even if all we do is point people to PEP 440. Perhaps something like "Invalid version: {0}. (See PEP 440 for guidance)". Even then it feels like we could do better still by detecting the reason(s) that a string is invalid and including those, perhaps with different exception subtypes for each kind of error.

**Comment by xavfernandez** [comment] 2017-04-10 11:28
I agree packaging should catch the `UnicodeEncodeError` and re-raise an `InvalidVersion`.

**Comment by dstufft** [comment] 2017-04-10 13:56
Seems reasonable to me.

**Comment by deveshks** [comment] 2020-04-24 14:40
The error is originating from when the logger tries to log the unicode version

https://github.com/pypa/packaging/blob/61672bf9f507f38e84ce2786a1c42f55fa0a3153/packaging/version.py#L275-L277

```
$ python
Python 2.7.16 (default, Apr  9 2020, 15:00:07) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> version = u'1.2.3+941_Добавить_на_ф'
>>> "Invalid version: '{0}'".format(u'1.2.3+941_Добавить_на_ф')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-17: ordinal not in range(128)

**Comment by brettcannon** [comment] 2020-04-24 18:03
@deveshks yeah, just need to add a `u` prefix to the argument for `InvalidVersion`.

I can't wait until we drop Python 2 support. 😝

**Comment by deveshks** [comment] 2020-04-24 18:26
> yeah, just need to add a `u` prefix to the argument for `InvalidVersion`.

I assume you are talking about adding a leading `u` prefix as follows

```
>>> version = u'1.2.3+941_Добавить_на_ф'
>>> u"Invalid version: '{0}'".format(u'1.2.3+941_Добавить_на_ф')
u"Invalid version: '1.2.3+941_\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c_\u043d\u0430_\u0444'"
```
But that causes the characters to be printed in their unicode representation, along with a leading `u` in the string?

**Comment by brettcannon** [comment] 2020-04-25 00:32
@deveshks that's fine. It's just the repr and it's not what human beings will see.

**Comment by deveshks** [comment] 2020-04-27 19:17
> @deveshks that's fine. It's just the repr and it's not what human beings will see.

So if I go ahead and apply the changes as mentioned

```diff
diff --git a/packaging/version.py b/packaging/version.py
index 00371e8..7cfdc48 100644
--- a/packaging/version.py
+++ b/packaging/version.py
@@ -274,7 +274,7 @@ class Version(_BaseVersion):
         # Validate the version and parse it into pieces
         match = self._regex.search(version)
         if not match:
-            raise InvalidVersion("Invalid version: '{0}'".format(version))
+            raise InvalidVersion(u"Invalid version: '{0}'".format(version))
 
         # Store the parsed out pieces of the version
         self._version = _Version(
```

We will try to instantiate `LegacyVersion`, but that will fail at `self._version = str(version)`  since we are trying to cast unicode to str.  

```
>>> v = u'1.2.3+941_Добавить_на_ф'
>>> from packaging import version
>>> version.parse(v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packaging/version.py", line 58, in parse
    return LegacyVersion(version)
  File "packaging/version.py", line 109, in __init__
    self._version = str(version)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-17: ordinal not in range(128)
```
https://github.com/pypa/packaging/blob/221443a8a9aa3bdc89726c01cf34e57159ba6ae7/packaging/version.py#L106-L110

What would the fix for this be. Should we change `self._version = repr(version)` so that a `LegacyVersion` is created? Or should we raise some other error so that the code doesn't go to `LegacyVersion` creation itself?

**Comment by brettcannon** [comment] 2020-04-27 23:59
I think the fix is to stop supporting Python 2. 😉

**Comment by pradyunsg** [comment] 2020-04-28 01:39
I agree with Brett here. It's probably not worth any of our limited volunteered developer time to fix this - unless someone affected by this really wants this fixed enough to file a PR.

If someone affected by this wants to help fix this before we drop Python 2 support, they're welcome to - it'll be subject to the regular review process.

**Comment by deveshks** [comment] 2020-04-28 03:24
> I think the fix is to stop supporting Python 2. 😉

Agreed. Once Python 2 support is dropped, which I assume should not be far away, this issue won't arise.

**Comment by brettcannon** [comment] 2021-03-24 20:29
Python 2 support is gone, so I'm closing this on the assumption that it's no longer an issue.

**Closed by brettcannon** 2021-03-24 20:29 UTC
Labels: bug, packaging.version
